
/**
    @file city_model.h
    @a class that tracks the cities 
    @author Mike Neergaard <mike.neergaard@gmail.com>
    @version 1.0

    @section LICENSE
    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.

    Copyright (C) 2015  Mike Neergaard

*/

#ifndef thai_names_H
#define thai_names_H

static s_name THAI_name[]{
{"กนกพร", "Ganokpon"},
{"กมล", "Gamon"},
{"กระสินธ์", "Grasin"},
{"กฤษฏิ์", "Krist"},
{"กล้าหาญ", "Klaharn"},
{"กาญจนา", "Kanchana"},
{"กานดา", "Gaan-daa"},
{"กุญชนิตา", "Kunchanita"},
{"กุมโชค", "Kumchok"},
{"กุลพันธ์", "Kunlapan"},
{"เกษม", "Kasem"},
{"แก้วเก้า", "Gaewgaow"},
{"ขจี", "Khajee"},
{"ขนิษฐา", "Khanittha"},
{"ขวัญจิต", "Khwanchit"},
{"ขวัญใจ", "Kwanjai"},
{"ขวัญชัย", "Kwanchai"},
{"คลัง", "Khlang"},
{"จตุพล", "Chatuphon"},
{"จักรี", "Chakrii"},
{"จันทร์สิริ", "Chanthasiri"},
{"จารุวรรณ", "Jaruwan"},
{"จุลภาส", "Chunphat"},
{"เจือ", "Juaa"},
{"ฉลวย", "Chaluay"},
{"เฉลิม", "Chalerm"},
{"ชนะ", "Chana"},
{"ชนินทร์", "Chanin"},
{"ชนิภรณ์", "Chaniporn"},
{"ชมเกดุ", "Chomkate"},
{"ชวน", "Chuan"},
{"ชัยพร", "Chaiyaporn"},
{"ชัยอนันต์", "Chaiyanan"},
{"ชาญชัย", "Chanchai"},
{"ชาติ", "Chati"},
{"ชาติชาย", "Chatchai"},
{"ชิด", "Chid"},
{"ชุ่ม", "Choom"},
{"ชูวิทย์", "Chuwit"},
{"เชาวน์", "Chaow"},
{"เซติยัง", "Setiyang"},
{"เซติอาวัน", "Setiawan"},
{"ญาณิน", "Yanin"},
{"ฐิตวรรณ", "Thitawan"},
{"ฐิติภรณ์", "Thitiporn"},
{"ณรงค์ศักดิ์", "Narongsak"},
{"ณัฎฐา", "Nuttha"},
{"ณัฐิมา", "Nuttima"},
{"ณี", "Nee"},
{"ดนัย", "Danai"},
{"ดวงกมล", "Duangkamol"},
{"ดวงใจ", "Duangjai"},
{"ดุสิต", "Dusit"},
{"เดือนเพ็ญ", "Duanphen"},
{"แดง", "Dang"},
{"ตนุพล", "Tanuphon"},
{"ถนัด", "Thanat"},
{"ถวิล", "Thawin"},
{"ทวีฉัตร", "Thawichat"},
{"ทวีป", "Thawip"},
{"ทวีวงศ์", "Thawiwong"},
{"ทวีศักดิ์", "Thawisak"},
{"ทักษิณ", "Thaksin"},
{"ทัศนีย์", "Tussanee"},
{"ธงชัย", "Thongchai"},
{"ธนากร", "Thanakorn"},
{"ธนาพร", "Thanaporn"},
{"ธเนศ", "Tanet"},
{"ธีรภัทร", "Thinphat"},
{"ธีรศักดิ์", "Teerasak"},
{"นงนุช", "Nongnut"},
{"นงลักษณ์", "Nongluck"},
{"นพคุณ", "Nopadon"},
{"นพดล", "Nopadol"},
{"นพรัตน์", "Nopparat"},
{"นภสร", "Napasorn"},
{"นรินทร์ศักดิ์", "Narinsak"},
{"นริศา", "Narisa"},
{"นฤมล", "Naruemol"},
{"นววรรณ", "Nawawan"},
{"นัยนา", "Naiyana"},
{"นาก", "Nak"},
{"นาค", "Naak"},
{"นิตยา", "Nittaya"},
{"นีราชา", "Niracha"},
{"เนาวรัตน์", "Naowarat"},
{"บัญญัติ", "Banyat"},
{"บัณฑิตา", "Banthita"},
{"บุญยง", "Bunyong"},
{"บุญเยี่ยม", "Bunyiam"},
{"บุญรัตน์", "Bunrat"},
{"บุญศรี", "Boonsri"},
{"บุศวรรณ", "Busawan"},
{"บุษราคัม", "Busarakham"},
{"ปฏิภาณ", "Patipaan"},
{"ปฐม", "Pathom"},
{"ประชา", "Pracha"},
{"ประดิษฐ์", "Pradit"},
{"ประทีป", "Prathip"},
{"ประทุม", "Prathum"},
{"ประพันธ์", "Praphan"},
{"ประภาส", "Praphat"},
{"ประมนต์", "Pramon"},
{"ประมุข", "Pramuk"},
{"ประวิตร", "Prawit"},
{"ประวิทย์", "Prawit"},
{"ประเวช", "Prawet"},
{"ประเวศ", "Prawet"},
{"ประสงค์", "Prasong"},
{"ประสาน", "Prasan"},
{"ประสิทธิ", "Prasit"},
{"ประเสริฐ", "Prasert"},
{"ปรัชญา", "Pratya"},
{"ปราณี", "Pranee"},
{"ปริญญา", "Parinya"},
{"ปรีชา", "Preechaa"},
{"ปรีดา", "Preeda"},
{"ปวีณา", "Pavena"},
{"ป้อง", "Pong"},
{"ปัญญา", "Punyaa"},
{"ปานใจ", "Panchai"},
{"ปานเทพ", "Panthep"},
{"ปาริชาติ", "Parichat"},
{"ปิติ", "Piti"},
{"ปิยบุตร", "Piyabut"},
{"ปิยวรรณ", "Piyawan"},
{"ปิยะคม", "Piyakom"},
{"ปีติ", "Piti"},
{"ปีย์รติ", "Perati"},
{"เปรม", "Prem"},
{"ผ่องเพ็ญ", "Phongphen"},
{"ผาณิต", "Panit"},
{"เผด็จ", "Phadet"},
{"พนม", "Panom"},
{"พนิต", "Panit"},
{"พยนต์", "Phayon"},
{"พรชัย", "Pornchai"},
{"พรพรรณ", "Phonphan"},
{"พรพันธุ์", "Phonphan"},
{"พรรณี", "Pannee"},
{"พรรัมภา", "Phornrampha"},
{"พลเดช", "Phondet"},
{"พัชรพร", "Patcharabhorn"},
{"พัฒนา", "Pattana"},
{"พาณิชย์", "Phanit"},
{"พาที", "Pathi"},
{"พิกุล", "Pikun"},
{"พิจิตร", "Phichit"},
{"พิชิต", "Phichit"},
{"พินิจ", "Phinit"},
{"พิภพ", "Phiphop"},
{"พิมพ์ใจ", "Phimchai"},
{"พิมพ์วสี", "Pimwasee"},
{"พิริยะ", "Phiriya"},
{"พูนศักดิ์", "Phunsak"},
{"เพ็ญสุขภรณ์", "Pensukporn"},
{"เพิ่ม", "Perm"},
{"ไพฑูรย์", "Paithoon"},
{"ไพบูลย์", "Phaibun"},
{"ไพรัช", "Pairat"},
{"ไพศักดิ์", "Phaisak"},
{"ไพศาล", "Phaisan"},
{"ฟุ้งฟ้า", "Fungfaa"},
{"ภรณ์พรรณ", "Phonphan"},
{"ภรณ์พันธ์", "Phonphan"},
{"ภรณ์พันธุ์", "Phonphan"},
{"ภานุพัฒน์", "Panupat"},
{"ภาสุระ", "Pasura"},
{"ภิรมย์", "Phirom"},
{"ภุชงค์", "Phuchong"},
{"ภูมินทร์", "Phumin"},
{"ภูมิพัฒน์", "Phumphat"},
{"มงคล", "Mongkhon"},
{"มณี", "Manee"},
{"มณู", "Manoo"},
{"มนตรี", "Montri"},
{"มนู", "Manu"},
{"มโน", "Mano"},
{"มะลิ", "Mali"},
{"มาณี", "Manee"},
{"มานิจ", "Manit"},
{"มานิตย์", "Marnit"},
{"มารวย", "Maruai"},
{"มาลี", "Malee"},
{"มุกดา", "Mukda"},
{"ยิ่งยศ", "Yingyot"},
{"ยุทธ์", "Yut"},
{"ยุพิน", "Yupin"},
{"ยุวรัตน์", "Yuwarat"},
{"เยาวพา", "Yaowapha"},
{"รอง", "Rong"},
{"รัตน์", "Rut"},
{"ราม", "Ram"},
{"รินรดา", "Rinrada"},
{"รื่น", "Rune"},
{"รื่นฤดี", "Runerudee"},
{"รุ่งสิทธิ์", "Rungsit"},
{"ฤดี", "Rudee"},
{"ฤทัย", "Ruthai"},
{"วรพร", "Woraporn"},
{"วรภัทร", "Vorapat"},
{"วรรณ", "Wann"},
{"วรรณา", "Wanna"},
{"วราภรณ์", "Waraporn"},
{"วัชราภรณ์", "Watcharaporn"},
{"วัฒนา", "Wattana"},
{"วันพล", "Wanpol"},
{"วัลลภ", "Wanlop"},
{"วัลลภา", "Wanlapa"},
{"วานี", "Wanee"},
{"วิจารณ์", "Wichan"},
{"วิจิตร", "Wichit"},
{"วิชัย", "Wichai"},
{"วิเชียร", "Wichian"},
{"วิทยา", "Witya"},
{"วินัย", "Winai or Vinai"},
{"วิภา", "Wipa"},
{"วิภาภรณ์", "Wipaporn"},
{"วิรัช", "Wirat"},
{"วิริยะ", "Wiriya"},
{"วิโรจน์", "Viroj"},
{"วิลาศ", "Wilat"},
{"วิศิษฏ์", "Wisit"},
{"วิเศษ", "Wiset"},
{"วีรยุทธ์", "Winyut"},
{"วีรศักดิ์", "Wirasak"},
{"วีระ", "Veera"},
{"วีระ", "Wira"},
{"วีระชาติ", "Wirachat"},
{"วีระชาย", "Wirachai"},
{"วีระพล", "Wiraphon"},
{"วีระพันธุ์", "Wiraphan"},
{"วีระศักดิ์", "Wirasak"},
{"ศรีศักดิ์", "Sisak"},
{"ศศิธร", "Sasithorn"},
{"ศักดา", "Sakada"},
{"ศักดิ์ทิพย์", "Sakthip"},
{"ศิริ", "Siri"},
{"ศิริโชค", "Sirichok"},
{"ศิริณี", "Sirini"},
{"ศิริพงศ์", "Siriphong"},
{"ศิริพร", "Siriporn"},
{"ศิริพล", "Siriphon"},
{"ศิริรัตน์", "Sirirat"},
{"ศิริวรรณ", "Siriwan"},
{"ศุภชัย", "Supachai"},
{"ศุภผล", "Suppaphon"},
{"ศุภรัตน์", "Supparat"},
{"ศุภวิทย์", "Supawit"},
{"ศุภวุฒิ", "Suphawut"},
{"สกุล", "Sakun"},
{"สนธิ", "Sonthi"},
{"สนั่น", "Sanan"},
{"สนิท", "Sanit"},
{"สมควร", "Somkhuan"},
{"สมคิด", "Somkhit"},
{"สมจิต", "Somjit"},
{"สมชาย", "Somchai"},
{"สมโชค", "Somchok"},
{"สมทรง", "Somsong"},
{"สมบัติ", "Sombat"},
{"สมบุญ", "Sombun"},
{"สมบูรณ์", "Somboon"},
{"สมพงษ์", "Sompong"},
{"สมพร", "Somporn"},
{"สมเพียร", "Somphian"},
{"สมภพ", "Somphop"},
{"สมยศ", "Somyot"},
{"สมร", "Samorn"},
{"สมรัตน์", "Somrat"},
{"สมลักษณ์", "Somlaksa"},
{"สมศรี", "Somsri"},
{"สมศักดิ์", "Somsak"},
{"สมหมาย", "Sommai"},
{"สมัคร", "Samak"},
{"สริตา", "Sarita"},
{"สลิลธร", "Saliltorn"},
{"สวัสดิ์", "Sawat"},
{"สว่าง", "Sawang"},
{"สังวาล", "Sangwaan"},
{"สันติ", "Santi"},
{"สากล", "Sakon"},
{"สาธิต", "Sathit"},
{"สาธิตยัง", "Sathittayang"},
{"สามารถ", "Samat"},
{"สายพิณ", "Saiphin"},
{"สายสมร", "Saisamorn"},
{"สาวิทย์", "Sawit"},
{"สิงห์", "Singh"},
{"สิทธิ", "Sitthi"},
{"สิริกิติ์", "Sirikit"},
{"สิริรักษ์", "Sirirak"},
{"สีห์ศักดิ์", "Sisak"},
{"สุกัญญา", "Sugunya"},
{"สุจิต", "Sujit"},
{"สุจินดา", "Suchinda"},
{"สุชาดา", "Suchada"},
{"สุชาดาจะ", "Suchadacha"},
{"สุชาติ", "Suchart"},
{"สุชาย", "Suchai"},
{"สุดใจ", "Somjai"},
{"สุดา", "Suda"},
{"สุทธิพงศ์", "Sutthiphong"},
{"สุทธิพล", "Sutthiphon"},
{"สุเทพ", "Suthep"},
{"สุธรรม", "Sutham"},
{"สุนทรี", "Soontharee"},
{"สุนัย", "Sunai"},
{"สุนี", "Suni"},
{"สุนีย์", "Sunee"},
{"สุประภา", "Suprapha"},
{"สุพรรณ", "Suphan"},
{"สุพิชา", "Supicha"},
{"สุพิศ", "Supit"},
{"สุภาพ", "Suphap"},
{"สุภาภรณ์", "Supaporn"},
{"สุเมธ", "Sumate"},
{"สุรัตน์", "Surat"},
{"สุริยะ", "Suriya"},
{"สุริยา", "Suriya"},
{"สุรี", "Suree"},
{"สุวรรณ", "Suwan"},
{"สุวิชา", "Suwicha"},
{"สุวิทย์", "Suwit"},
{"สุหัตถ์", "Suhat"},
{"เสรี", "Seri"},
{"แสงดาว", "Saengdow"},
{"โสภาค", "Sobhak"},
{"หทัย", "Hathai"},
{"หนิว", "Niew"},
{"อดิศักดิ์", "Adisak"},
{"อนันต์", "Anan"},
{"อนันตชัย", "Anantachai"},
{"อนุชา", "Anucha"},
{"อภิชาต", "Aphichat"},
{"อภิชาติ", "Aphichat"},
{"อภิญญา", "Apinya"},
{"อภิรักษ์", "Aphirak"},
{"อภิศักดิ์", "Aphisak"},
{"อภิสิทธิ์", "Abhisit"},
{"อมร", "Amorn"},
{"อมรรัตน์", "Amornrat"},
{"อริศรา", "Alisara"},
{"อรุณศรี", "Arunsri"},
{"อักขระ", "Akara"},
{"อัญญาณี", "Unyanee"},
{"อัษฎา", "Asda"},
{"อัษรา", "Asara"},
{"อาณัติ", "Anat"},
{"อาทิตย์", "Arthit"},
{"อารง", "Arong"},
{"อารี", "Aree"},
{"อารีพงศ์", "Ariphong"},
{"อุกฤษฏ์", "Ukrit"},
{"อุกิต", "Ukit"},
{"อุดม", "Udom"},
{"อุบล", "Ubol"},
{"อุบลวรรณ", "Ubonwan"},
{"เอกพงษ์", "Ekaphong"},
{"เอกใหม่", "Ekamai"}, {"สุภา", "Supa"} };

/// This class gives us the names
class thai
{ public:
  static std::string give_name(int index) {
    int surnames = 361;
    std::string ret_val;
    ret_val = THAI_name[index].name + " ("+THAI_name[index].roman_name +")";
    return ret_val;
  }


  static int select_name(double p) {
    // Takes a double uniformly distributed in [0,1)
    // enforce boundaries
    if (p < 0) return 0;
    if (p >= 1) return 42;

  int ret_val = (361*p);

    // In theory, (int) p*x*y will never actually be x*y,
    return ret_val;
  }
};
#endif
